version: '2'
services:
  web:
    image: ${IMAGE_NAME}
    ports:
      - "3000"
    networks:
       - ci
    labels:
      - "traefik.backend=beta-landing-page"
      - "traefik.frontend.rule=Host:beta-landing-pageci.ukpds.org"

networks:
  ci:
    external: true